import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { generateAgentResponse } from '@/lib/openai'
import { prisma } from '@/lib/prisma'

const AGENT_SYSTEM_PROMPTS: Record<string, string> = {
  News: `You are a news content agent. Given a topic or headline, generate an engaging social media post. Keep it concise, informative, and suitable for professional audiences. Include relevant hashtags.`,
  Communication: `You are an email communication agent. Draft professional, clear, and concise emails. Match the tone to the context — formal for business, friendly for colleagues.`,
  Finance: `You are a financial analysis agent. Analyze spending patterns, flag anomalies, and provide clear summaries. Be precise with numbers and conservative with recommendations.`,
  Research: `You are a research agent. Compile clear, well-sourced summaries on given topics. Focus on key findings, cite sources, and highlight implications.`,
  Scheduling: `You are a scheduling optimization agent. Suggest meeting times, resolve conflicts, and optimize calendar blocks. Consider time zones and priorities.`,
  Health: `You are a health monitoring agent. Provide wellness insights based on health data. Be supportive, evidence-based, and always recommend consulting healthcare providers for medical decisions.`,
  Legal: `You are a legal document review agent. Highlight key terms, risks, and obligations. Flag unusual clauses. Always note that this is not legal advice.`,
}

export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions)
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Not authenticated. Please log in.' }, { status: 401 })
  }

  const body = await req.json()
  const { agentId, prompt } = body

  if (!agentId || !prompt) {
    return NextResponse.json({ error: 'agentId and prompt required' }, { status: 400 })
  }

  // Verify agent belongs to user
  const agent = await prisma.agent.findFirst({
    where: { id: agentId, userId: session.user.id },
  })

  if (!agent) {
    return NextResponse.json({ error: 'Agent not found' }, { status: 404 })
  }

  // Get user's API key from settings, fall back to server env var
  const user = await prisma.user.findUnique({ where: { id: session.user.id } })
  let apiKey: string | undefined
  try {
    const settings = JSON.parse(user?.settings || '{}')
    apiKey = settings.openaiApiKey || process.env.OPENAI_API_KEY || undefined
  } catch {
    apiKey = process.env.OPENAI_API_KEY || undefined
  }

  if (!apiKey) {
    return NextResponse.json(
      { error: 'OpenAI API key not configured. Add it in Settings or set OPENAI_API_KEY on Vercel.' },
      { status: 400 }
    )
  }

  try {
    const systemPrompt = AGENT_SYSTEM_PROMPTS[agent.category] ||
      `You are an AI agent named ${agent.name} in the ${agent.category} category. ${agent.description}`

    const content = await generateAgentResponse(prompt, systemPrompt, apiKey)

    // Create an approval item for the generated content
    const approval = await prisma.approvalItem.create({
      data: {
        agentId: agent.id,
        action: `AI-generated: ${prompt.slice(0, 80)}`,
        detail: content,
        urgency: 'medium',
        reasoning: `Generated by ${agent.name} via OpenAI. Requires review before publishing.`,
      },
    })

    // Log the activity
    await prisma.activityLog.create({
      data: {
        agentId: agent.id,
        action: `Generated content: "${prompt.slice(0, 60)}"`,
        type: 'auto',
        category: agent.category,
        detail: `AI-generated content created and sent to approval queue.`,
        metadata: JSON.stringify({ approvalId: approval.id, model: 'gpt-4o-mini' }),
      },
    })

    return NextResponse.json({
      success: true,
      content,
      approvalId: approval.id,
      message: 'Content generated and sent to approval queue.',
    })
  } catch (err) {
    console.error('Generate API error:', err)
    const message = err instanceof Error ? err.message : 'Generation failed'
    if (message.includes('Incorrect API key') || message.includes('invalid_api_key')) {
      return NextResponse.json({ error: 'Invalid OpenAI API key. Check your key in Settings or Vercel environment variables.' }, { status: 401 })
    }
    if (message.includes('quota') || message.includes('rate_limit') || message.includes('insufficient_quota')) {
      return NextResponse.json({ error: 'OpenAI API quota exceeded or rate limited. Check your OpenAI billing.' }, { status: 429 })
    }
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
